[global]
port = 9005
# timeout in seconds for fetching web things
timeout = 3

[proxies]
# remove expired proxies when <expire-days> passes by 
expire-days = 7
sites = [
        {       name = "nodefree", url = "{{date_current('https://nodefree.org/dy/%Y/%m/%Y%m%d.yaml')}}" },
        {       name = "clashnode", url = "{{date_current('https://clashnode.com/wp-content/uploads/%Y/%m/%Y%m%d.yaml')}}" }
]
